version: "3.7"

services:
  postgis:
    image: postgis/postgis
    container_name: postgis_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=earhquakes
    volumes:
      - postgis_data_earthquake:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgis_data_earthquake:
